### ISSUE TITLE
Create standup notes template

### ISSUE THREAD

**Issue by t9guan** [t9guan/sp21-cse110-lab3#2]
**Tasks**
- [ ] Create standup notes template
- [ ] Add styling to journal entry #1
- [ ] Add styling to journal entry #2
- [ ] Add styling to journal entry #3

**Other additional tasks**
